version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/alan-mak/jungle-rails.git master:production
      - ruby/bundle-install
