version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5-stretch
    executor: ruby/default
    steps:
      - checkout
      - run:
           name: Set ruby version to 2.3.5
           command: |
                rvm install 2.3.5
                echo . $(rvm 2.3.5 do rvm env --path) >> $BASH_ENV