version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Set ruby version
          command: echo "ruby-2.3.5" > ~/.ruby-version
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
